name: Generate Snake

on:
  schedule:
    # runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake animation files
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Tantalost
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Commit the generated files if there are changes
      - name: Commit generated snake files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.gif
          git commit -m "Update snake animation" || echo "No changes to commit"

      # Push the committed files to the master branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # (Optional) Publish the dist folder to the output branch as GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
